#!/bin/bash
# Quick deployment script for Vercel

echo "🚀 Nivaas Deployment Guide"
echo "=========================="
echo ""
echo "STEP 1: Push to GitHub"
echo "  $ git init"
echo "  $ git add ."
echo "  $ git commit -m 'Initial commit'"
echo "  $ git branch -M main"
echo "  $ git remote add origin https://github.com/YOUR_USERNAME/nivaas.git"
echo "  $ git push -u origin main"
echo ""
echo "STEP 2: Deploy Backend (Railway)"
echo "  1. Go to https://railway.app/new"
echo "  2. Select 'Deploy from GitHub'"
echo "  3. Select your nivaas repo"
echo "  4. Add PostgreSQL database"
echo "  5. Set environment variables (see Railway dashboard)"
echo "  6. Get public API URL (e.g., https://nivaas-api.railway.app)"
echo ""
echo "STEP 3: Deploy Frontend (Vercel)"
echo "  1. Go to https://vercel.com/new"
echo "  2. Click 'Import Project'"
echo "  3. Paste your GitHub repo URL"
echo "  4. In 'Environment Variables', add:"
echo "     - NEXT_PUBLIC_API_URL = https://nivaas-api.railway.app"
echo "  5. Click 'Deploy'"
echo ""
echo "✅ Done! Your app is live at https://nivaas.vercel.app"
echo ""
echo "To make it faster, skip the backend for now:"
echo "  - Deploy frontend only to Vercel"
echo "  - Forms will log to console but won't persist"
echo "  - Deploy backend later when ready"
