export type FurnishingType = "Fully Furnished" | "Semi Furnished" | "Unfurnished"

export type NearbyPlace = {
  name: string
  type: "IT Park" | "Mall" | "Hospital" | "School" | "Transit"
  distance: string
}

export type Listing = {
  id: string
  name: string
  tower: string
  address: string
  locality: string
  city: string
  pincode: string
  bhk: number
  rent: number
  deposit: number
  maintenance: number
  areaSqft: number
  bathrooms: number
  balconies: number
  furnishing: FurnishingType
  floor: string
  rating: number
  reviews: number
  reraVerified: boolean
  fieldVerified: boolean
  parking: boolean
  petFriendly: boolean
  availableFrom: string
  ownerName: string
  ownerType: "Owner" | "Nivaas Managed"
  phone: string
  itParkDistance: string
  videoTour: boolean
  images: string[]
  amenities: string[]
  nearby: NearbyPlace[]
  description: string
}

const INTERIORS = [
  "/images/apt-2.png",
  "/images/apt-3.png",
  "/images/apt-4.png",
  "/images/apt-7.png",
]

export const AMENITY_OPTIONS = [
  "24x7 Security",
  "Power Backup",
  "Covered Parking",
  "Gymnasium",
  "Swimming Pool",
  "Clubhouse",
  "Lift",
  "Children's Play Area",
  "Modular Kitchen",
  "Piped Gas",
  "RO Water Purifier",
  "Wi-Fi Ready",
  "Air Conditioning",
  "Housekeeping",
]

const COMMON_NEARBY: NearbyPlace[] = [
  { name: "Rajiv Gandhi Infotech Park", type: "IT Park", distance: "1.5 km" },
  { name: "Grand Highstreet Mall", type: "Mall", distance: "2.2 km" },
  { name: "Lifepoint Multispeciality Hospital", type: "Hospital", distance: "1.8 km" },
  { name: "Blue Ridge Public School", type: "School", distance: "1.1 km" },
  { name: "Hinjewadi Metro (Line 3)", type: "Transit", distance: "0.9 km" },
]

export const listings: Listing[] = [
  {
    id: "megapolis-sangria",
    name: "Megapolis Sangria Towers",
    tower: "Tower C",
    address: "Megapolis Township, Rajiv Gandhi Infotech Park",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 32000,
    deposit: 96000,
    maintenance: 3200,
    areaSqft: 1050,
    bathrooms: 2,
    balconies: 2,
    furnishing: "Fully Furnished",
    floor: "9th of 23",
    rating: 4.8,
    reviews: 64,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Rakesh Menon",
    ownerType: "Nivaas Managed",
    phone: "+91 98220 41200",
    itParkDistance: "5 min to Wipro Circle",
    videoTour: true,
    images: ["/images/apt-1.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Swimming Pool",
      "Clubhouse",
      "Lift",
      "Modular Kitchen",
      "Piped Gas",
      "Air Conditioning",
    ],
    nearby: COMMON_NEARBY,
    description:
      "A bright, fully furnished 2 BHK inside Hinjewadi's flagship Megapolis township. Walk to Wipro and Infosys campuses, with a modular kitchen, split ACs in both bedrooms, and access to a clubhouse, pool, and gym.",
  },
  {
    id: "megapolis-splendour",
    name: "Megapolis Splendour",
    tower: "Tower B",
    address: "Megapolis Township, Rajiv Gandhi Infotech Park",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 27500,
    deposit: 82500,
    maintenance: 2800,
    areaSqft: 980,
    bathrooms: 2,
    balconies: 1,
    furnishing: "Semi Furnished",
    floor: "6th of 18",
    rating: 4.6,
    reviews: 41,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: false,
    availableFrom: "1 Aug 2026",
    ownerName: "Sunita Deshpande",
    ownerType: "Owner",
    phone: "+91 99700 55831",
    itParkDistance: "8 min to Infosys Phase 2",
    videoTour: true,
    images: ["/images/apt-5.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Clubhouse",
      "Lift",
      "Children's Play Area",
      "Piped Gas",
      "RO Water Purifier",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Semi-furnished 2 BHK with wardrobes, modular kitchen, and geysers installed. Quiet tower within Megapolis with quick access to the Hinjewadi-Shivajinagar metro line.",
  },
  {
    id: "mont-vert-belair",
    name: "Mont Vert Belair",
    tower: "Wing D",
    address: "Marunji Road, near Rajiv Gandhi Infotech Park",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 24000,
    deposit: 72000,
    maintenance: 2400,
    areaSqft: 910,
    bathrooms: 2,
    balconies: 1,
    furnishing: "Semi Furnished",
    floor: "3rd of 12",
    rating: 4.4,
    reviews: 28,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Imran Shaikh",
    ownerType: "Nivaas Managed",
    phone: "+91 97640 12093",
    itParkDistance: "10 min to Rajiv Gandhi Infotech Park",
    videoTour: false,
    images: ["/images/apt-6.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Lift",
      "Children's Play Area",
      "Piped Gas",
      "Wi-Fi Ready",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Well-maintained semi-furnished 2 BHK on Marunji Road with a green, low-density campus. Pet friendly with covered parking and reliable power backup.",
  },
  {
    id: "rohan-ananta",
    name: "Rohan Ananta",
    tower: "Tower 4",
    address: "Tathawade-Hinjewadi Link Road",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 3,
    rent: 41000,
    deposit: 123000,
    maintenance: 4100,
    areaSqft: 1320,
    bathrooms: 3,
    balconies: 2,
    furnishing: "Fully Furnished",
    floor: "14th of 20",
    rating: 4.7,
    reviews: 37,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "15 Aug 2026",
    ownerName: "Priya Nair",
    ownerType: "Nivaas Managed",
    phone: "+91 98905 77410",
    itParkDistance: "12 min to Wipro Circle",
    videoTour: true,
    images: ["/images/apt-8.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Swimming Pool",
      "Clubhouse",
      "Lift",
      "Modular Kitchen",
      "Air Conditioning",
      "Housekeeping",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Spacious high-floor 3 BHK with skyline views, fully furnished with ACs, beds, and a modular kitchen. Premium amenities including pool, clubhouse, and daily housekeeping.",
  },
  {
    id: "kasturi-eon-homes",
    name: "Kasturi Eon Homes",
    tower: "Wing A",
    address: "Near Wipro Circle, Rajiv Gandhi Infotech Park",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 1,
    rent: 18500,
    deposit: 55500,
    maintenance: 1800,
    areaSqft: 620,
    bathrooms: 1,
    balconies: 1,
    furnishing: "Fully Furnished",
    floor: "5th of 15",
    rating: 4.5,
    reviews: 52,
    reraVerified: true,
    fieldVerified: true,
    parking: false,
    petFriendly: false,
    availableFrom: "Immediate",
    ownerName: "Amit Kulkarni",
    ownerType: "Owner",
    phone: "+91 90110 26654",
    itParkDistance: "3 min to Wipro Circle",
    videoTour: true,
    images: ["/images/apt-1.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Gymnasium",
      "Lift",
      "Modular Kitchen",
      "Piped Gas",
      "Air Conditioning",
      "Wi-Fi Ready",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Compact fully furnished 1 BHK a short walk from Wipro Circle. Move-in ready with AC, bed, sofa, and modular kitchen.",
  },
  {
    id: "xrbia-hinjewadi",
    name: "Xrbia Hinjewadi Road",
    tower: "Cluster 2",
    address: "Hinjewadi-Marunji Road",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 21000,
    deposit: 63000,
    maintenance: 2100,
    areaSqft: 860,
    bathrooms: 2,
    balconies: 1,
    furnishing: "Unfurnished",
    floor: "8th of 16",
    rating: 4.2,
    reviews: 19,
    reraVerified: false,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "1 Sep 2026",
    ownerName: "Vikram Rao",
    ownerType: "Owner",
    phone: "+91 96570 33218",
    itParkDistance: "15 min to Infosys Phase 2",
    videoTour: false,
    images: ["/images/apt-5.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Lift",
      "Children's Play Area",
      "Piped Gas",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Affordable unfurnished 2 BHK for tenants who want to bring their own setup. Field-verified property with covered parking and pet friendly.",
  },
  {
    id: "emaar-mgf-palm-gardens",
    name: "Emaar MGF Palm Gardens",
    tower: "Tower G",
    address: "Hinjewadi Phase 3, Pune",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 3,
    rent: 45000,
    deposit: 135000,
    maintenance: 4500,
    areaSqft: 1400,
    bathrooms: 3,
    balconies: 2,
    furnishing: "Fully Furnished",
    floor: "12th of 25",
    rating: 4.9,
    reviews: 78,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Neha Singh",
    ownerType: "Nivaas Managed",
    phone: "+91 98765 43210",
    itParkDistance: "7 min to Infosys",
    videoTour: true,
    images: ["/images/apt-1.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Swimming Pool",
      "Clubhouse",
      "Lift",
      "Modular Kitchen",
      "Air Conditioning",
      "Housekeeping",
      "Piped Gas",
      "RO Water Purifier",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Premium 3 BHK in a gated community with world-class amenities. High-rise tower with scenic views, fully furnished with modular kitchen and AC in all rooms.",
  },
  {
    id: "lodha-ending-point",
    name: "Lodha Ending Point",
    tower: "Tower 5",
    address: "Kharadi, near Hinjewadi Phase 3",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 29000,
    deposit: 87000,
    maintenance: 2900,
    areaSqft: 950,
    bathrooms: 2,
    balconies: 1,
    furnishing: "Semi Furnished",
    floor: "10th of 19",
    rating: 4.6,
    reviews: 45,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: false,
    availableFrom: "Immediate",
    ownerName: "Raj Patel",
    ownerType: "Owner",
    phone: "+91 98234 56789",
    itParkDistance: "10 min to Wipro",
    videoTour: true,
    images: ["/images/apt-4.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Lift",
      "Modular Kitchen",
      "Air Conditioning",
      "Wi-Fi Ready",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Well-planned 2 BHK semi-furnished flat in a quality project. Modern amenities, gym, 24/7 security, and backup power.",
  },
  {
    id: "godrej-garden-city",
    name: "Godrej Garden City",
    tower: "Tower 1",
    address: "Hinjewadi Phase 3, Tathawade",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 1,
    rent: 16000,
    deposit: 48000,
    maintenance: 1600,
    areaSqft: 550,
    bathrooms: 1,
    balconies: 1,
    furnishing: "Semi Furnished",
    floor: "7th of 18",
    rating: 4.3,
    reviews: 31,
    reraVerified: true,
    fieldVerified: true,
    parking: false,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Deepak Kumar",
    ownerType: "Nivaas Managed",
    phone: "+91 97890 12345",
    itParkDistance: "12 min to Infosys",
    videoTour: false,
    images: ["/images/apt-3.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Gymnasium",
      "Lift",
      "Children's Play Area",
      "Piped Gas",
      "RO Water Purifier",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Compact 1 BHK semi-furnished flat perfect for bachelors or couples. Pet-friendly property with basic amenities and easy connectivity.",
  },
  {
    id: "shapoorji-pallonji-joyville",
    name: "Shapoorji Pallonji Joyville",
    tower: "Tower 8",
    address: "Hinjewadi Phase 3",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 35000,
    deposit: 105000,
    maintenance: 3500,
    areaSqft: 1100,
    bathrooms: 2,
    balconies: 2,
    furnishing: "Fully Furnished",
    floor: "11th of 22",
    rating: 4.7,
    reviews: 55,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Anjali Sharma",
    ownerType: "Nivaas Managed",
    phone: "+91 99876 54321",
    itParkDistance: "6 min to Wipro",
    videoTour: true,
    images: ["/images/apt-8.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Swimming Pool",
      "Clubhouse",
      "Lift",
      "Modular Kitchen",
      "Air Conditioning",
      "Wi-Fi Ready",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Luxurious fully furnished 2 BHK with premium finishes and modern amenities. High-floor location with natural light and ventilation.",
  },
  {
    id: "hiranandani-thana",
    name: "Hiranandani Heritage",
    tower: "Tower 3",
    address: "Hinjewadi Phase 3, Pune",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 3,
    rent: 38000,
    deposit: 114000,
    maintenance: 3800,
    areaSqft: 1250,
    bathrooms: 3,
    balconies: 2,
    furnishing: "Semi Furnished",
    floor: "9th of 20",
    rating: 4.5,
    reviews: 42,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: false,
    availableFrom: "15 Aug 2026",
    ownerName: "Mahesh Verma",
    ownerType: "Owner",
    phone: "+91 98567 89012",
    itParkDistance: "9 min to Infosys",
    videoTour: true,
    images: ["/images/apt-6.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Swimming Pool",
      "Lift",
      "Children's Play Area",
      "Piped Gas",
      "Air Conditioning",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Spacious semi-furnished 3 BHK apartment with modular kitchen and modern design. Ideal for families with access to all amenities.",
  },
  {
    id: "prestige-lakeside-towers",
    name: "Prestige Lakeside Towers",
    tower: "Tower 2",
    address: "Hinjewadi Phase 3",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 1,
    rent: 20000,
    deposit: 60000,
    maintenance: 2000,
    areaSqft: 700,
    bathrooms: 1,
    balconies: 1,
    furnishing: "Fully Furnished",
    floor: "6th of 14",
    rating: 4.4,
    reviews: 38,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Priya Gupta",
    ownerType: "Nivaas Managed",
    phone: "+91 99123 45678",
    itParkDistance: "4 min to Wipro Circle",
    videoTour: true,
    images: ["/images/apt-2.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Lift",
      "Modular Kitchen",
      "Air Conditioning",
      "Wi-Fi Ready",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Fully furnished 1 BHK studio apartment in a premium complex. Perfect for working professionals. Close to shopping and dining options.",
  },
  {
    id: "oberoi-realty-infinity",
    name: "Oberoi Realty Infinity",
    tower: "Tower A",
    address: "Hinjewadi Phase 3, Pune",
    locality: "Hinjewadi Phase 3",
    city: "Pune",
    pincode: "411057",
    bhk: 2,
    rent: 33000,
    deposit: 99000,
    maintenance: 3300,
    areaSqft: 1000,
    bathrooms: 2,
    balconies: 1,
    furnishing: "Fully Furnished",
    floor: "8th of 21",
    rating: 4.8,
    reviews: 67,
    reraVerified: true,
    fieldVerified: true,
    parking: true,
    petFriendly: true,
    availableFrom: "Immediate",
    ownerName: "Vikram Singh",
    ownerType: "Nivaas Managed",
    phone: "+91 96789 01234",
    itParkDistance: "5 min to Infosys",
    videoTour: true,
    images: ["/images/apt-7.png", ...INTERIORS],
    amenities: [
      "24x7 Security",
      "Power Backup",
      "Covered Parking",
      "Gymnasium",
      "Swimming Pool",
      "Clubhouse",
      "Lift",
      "Modular Kitchen",
      "Air Conditioning",
      "Housekeeping",
    ],
    nearby: COMMON_NEARBY,
    description:
      "Luxurious fully furnished 2 BHK in a premium gated community. High-quality finishes, modular kitchen, split ACs, and premium furnishings.",
  },
]

export function getListing(id: string) {
  return listings.find((l) => l.id === id)
}

export function formatINR(n: number) {
  return `\u20B9${n.toLocaleString("en-IN")}`
}

export function rentLabel(l: Listing) {
  return `${formatINR(l.rent)}/mo`
}

export function bhkLabel(l: Listing) {
  return `${l.bhk} BHK`
}
